export const DATA_CATEGORY = {
  JOB: 'JOB',
  RAW_DATA: 'RAW_DATA',
  CONSTRAINT: 'CONSTRAINT',
  ROLLING: 'ROLLING'
}

export const DATAFRAME_STATUS = {
  BOUND: 'BOUND',
  UNBOUND: 'UNBOUND',
  DELETE: 'DELETE'
}

export const ALERT_TYPE = {
  ALERT_OFF: 'ALERT_OFF',
  ALERT_QUANTITY: 'ALERT_QUANTITY',
  ALERT_PERCENTAGE: 'ALERT_PERCENTAGE'
}

export const UPDATE_TYPE = {
  PRESET: 'PRESET',
  CUSTOM: 'CUSTOM',
  OFF: 'OFF'
}

export const NOTIFICATION = {
  DELAY: 'DELAY'
}

export const JOB_STATUS = {
  GENERAL: 'GENERAL',
  SCHEDULED: 'SCHEDULED',
  OVERDUE: 'OVERDUE',
  DELAY: 'DELAYED',
  OVERDUE_DELAY: 'OVERDUE_DELAY'
}

export const SIMULATION_RESULT = {
  FAILED: 'FAILED',
  COMPLETED: 'COMPLETED'
}
